yml modified

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,9 +41,21 @@ jobs:
           aws s3 sync ./data s3://scheme-ref-dev-data-copy
 
       - name: Start Glue Crawler
+        if: crawler
         run: |
           aws glue start-crawler --name rdm_solution_crawler
-
+          while true; do
+            state=$(aws glue get-crawler --name rdm_solution_crawler --query 'Crawler.State' --output text)
+            if [[ "$state" == "READY"]]; then
+              break
+            fi
+            if [[ "$state" == "FAILED" ]]; then
+              echo "Crawler failed to run."
+              exit 1
+            fi
+            echo "Crawler is still running. Waiting for it to complete."
+            sleep 60
+          done
       # - name: Wait for Glue Crawler to finish
       #   env:
       #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -55,11 +67,17 @@ jobs:
       #     while [[ $(aws glue get-crawler --name "${crawler_name}" --query "Crawler.State") =~ ^(RUNNING|STOPPING)$ ]]; do sleep 30; done
 
       - name : Start Glue Job
+        uses: aws-actions/aws-cli@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-2
+          args: glue start-job-run --job-name glue_job_poc
         # env:
         #   AWS_REGION: eu-west-2
         #   GLUE_JOB_NAME: glue_job_poc
         # run: |
         #   python -c "import boto3; client = boto3.client('events'); client.put_events(Entries=[{'Source': 'GlueApp', 'DetailType': 'Glue Crawler State Change', 'Detail': '{\"state\":\"READY\",\"crawlerName\":\"rdm_solution_crawler\"}'}])"
-        if: github.event.detail.crawlerName == 'rdm_solution_crawler' && github.event.detail.state == 'READY'
-        run: |
-          aws glue start-job-run --job-name glue_job_poc
+        #if: github.event.detail.crawlerName == 'rdm_solution_crawler' && github.event.detail.state == 'READY'
+        # run: |
+        #   aws glue start-job-run --job-name glue_job_poc
